#!/usr/bin/env bash

function error_and_die() {
  echo -e "kopsenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}

function warn_and_continue() {
  echo -e "kopsenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(which sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  curl ${TLS_OPT} "$@"
}

function jq() {
  if ! which jq 2>&1 >/dev/null; then
  if -x $(basename ${0})/jq
    local arch=${KOPSENV_ARCH:-amd64}
   case "$(uname -s)" in
  Darwin*)
    os="darwin_${KOPSENV_ARCH}"
    ;;
  MINGW64*)
    os="windows_${KOPSENV_ARCH}"
    ;;
  MSYS_NT*)
    os="windows_${KOPSENV_ARCH}"
    ;;
  CYGWIN_NT*)
    os="windows_${KOPSENV_ARCH}"
    ;;
  *)
    os="linux_${KOPSENV_ARCH}"
    ;;
esac

    jq "$@"
  fi
  jq "$@"
}
