#!/usr/bin/env bash

[ -n "${KOPSENV_DEBUG}" ] && set -x

echo "Usage: kopsenv <command> [<options>]

Commands:
   install       Install a specific version of Kops
   use           Switch a version to use
   uninstall     Uninstall a specific version of Kops
   list          List all installed versions
   list-remote   List all installable versions
"
