#!/usr/bin/env bash
set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x
source ${KOPSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: kopsenv list-remote" 1>&2
  exit 1
fi

curlw -sf https://releases.hashicorp.com/kops/ | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta)[0-9]+)?" | uniq
