#!/usr/bin/env bash
set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x
source ${KOPSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: kopsenv list-remote" 1>&2
  exit 1
fi

# This is a bit hacky since it's relying on the whitespace formatting of
# JSON output from the github API, but there's no other reasonable way to
# get a list of the current kops versions using only POSIX tools
curl -sL https://api.github.com/repos/kubernetes/kops/releases \
  | grep tag_name \
  | sed 's/",$//; s/^.*"//' \
  | sort -t. -rn -k1,1 -k2,2 -k3,3 -k4,4

# curl -sL https://api.github.com/repos/kubernetes/kops/releases | grep browser_download_url | grep linux
