#!/usr/bin/env bash

[ -n "${KOPSENV_DEBUG}" ] && set -x
source ${KOPSENV_ROOT}/libexec/helpers

[ ${#} -ne 0 ] \
  && error_and_die "usage: kopsenv list"

[ -d "${KOPSENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: kopsenv install"

[[ -x "${KOPSENV_ROOT}/versions" && -r "${KOPSENV_ROOT}/versions" ]] \
  || error_and_die "kopsenv versions directory is inaccessible!"

print_version () {
    if [ "$1" == "$(kopsenv-version-name)" ]; then
        echo "* $1 (set by $(kopsenv-version-file))"
    else
        echo "  $1"
    fi
}

for local_version in $(ls -1 "${KOPSENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3); do
    print_version ${local_version}
done
