#!/usr/bin/env bash

set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x
source ${KOPSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ]; then
  echo "usage: kopsenv list-remote" 1>&2
  exit 1
fi

platform="$(kops_platform)"
(( "$?" )) && exit $?

# Get releases from both the Invoca fork (https://github.com/Invoca/kops) and the upstream Kops repo (https://github
# .com/kubernetes/kops)
urls=("https://api.github.com/repos/kubernetes/kops/releases" "https://api.github.com/repos/Invoca/kops/releases")

all_versions=""

for url in "${urls[@]}"; do
  json=$(curl -s -L "$url?per_page=100")
  (( "$?" )) && exit $?

  versions=$(echo "$json" \
    | grep 'tag_name' \
    | sed -E 's/.*"tag_name": "([^"]+)",.*/\1/' \
    | grep -v -E '(alpha|beta|gamma)' \
    | sort -t. -rn -k1,1 -k2,2 -k3,3 -k4,4 \
    | uniq)

  all_versions+="$versions"$'\n'
done

# Print versions out in descending order, regardless of which repo they come from
echo "$all_versions" | sort -t. -rn -k1,1 -k2,2 -k3,3 -k4,4 | uniq
