#!/usr/bin/env bash
# Usage: kopsenv min-required
# Summary: Detect the minimal required version from *kops files
set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x

bailout() {
    >&2 echo "Error: Could not determine required_version based on your kops sources.
Make sure at least one of your *kops files includes a required version section like
kops {
  required_version = \">= 0.0.0\"
}

see https://www.kops.io/docs/configuration/kops.html for details

"

    exit 1
}

find_min_required() {
    local root="${1}"

    versions=$(grep -h -R required_version --include '*kops' "$root"/* | tr -c -d '0-9. ~=!<>' )

    if [[ $versions =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]* ]]; then
        found_min_required=${BASH_REMATCH[1]}

        if [[ $found_min_required =~ ^!=.+ ]]; then
            echo "Error: Min required version is a negation ($found_min_required) - we cannot guess the desired one."

            bailout
        else
            found_min_required=$(echo "$found_min_required" | tr -c -d '0-9.')

    #        echo "Min required version is detected as ${found_min_required}"
            echo "${found_min_required}"
            exit 0
        fi
    fi

    bailout
}

find_min_required "${KOPSENV_DIR}"